ITS ALIVE ITS ALIVE: userInput
SHOW ME THE MONEY: userInput   

YOUVE GOT TO ASK YOURSELF ONE QUESTION: userInput == 1
	I WISH I KNEW HOW TO QUIT YOU: userInput == 1
		SAY HELLO TO MY LITTLE FRIEND: userInput
	ILL BE BACK:
FRANKLY MY DEAR I DONT GIVE A DAMN: